# Generated by Django 4.2.7 on 2023-11-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_labels_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
    ]
