# Generated by Django 4.2.7 on 2023-12-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_lables_labelsrelations_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelsrelations',
            old_name='label',
            new_name='labels',
        ),
    ]
