# Generated by Django 4.2.7 on 2023-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_name'),
        ('tasks', '0008_rename_labels_labelsrelations_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.LabelsRelations', to='labels.label', verbose_name='Метки'),
        ),
    ]
