# Generated by Django 4.2.7 on 2023-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_options'),
        ('tasks', '0009_remove_task_label_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.LabelsRelations', to='labels.label', verbose_name='Метка'),
        ),
    ]
