# Generated by Django 4.2.7 on 2023-12-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
    ]
