# Generated by Django 4.2.7 on 2023-12-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_label_labelsrelations_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelsrelations',
            old_name='labels',
            new_name='label',
        ),
    ]
